//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UnitID { get; set; }
        public byte[] ItemImage { get; set; }
        public string Note { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifiyUserID { get; set; }
        public System.DateTime ModifiyDate { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
